//! Which experts stay in VRAM, and what that choice costs.
//!
//! This is the module the project stands on. llama.cpp's SYCL backend splits MoE layers
//! between CPU and GPU **statically**: you pick `--n-cpu-moe` by hand and it never changes.
//! MoEArc's claim is that a *dynamic* residency policy beats a static split on the same
//! hardware. That claim is either true or it is not, and it can be settled here — in
//! simulation, on a routing trace, with no GPU involved.
//!
//! # Why simulate at all
//!
//! Writing SYCL kernels to find out whether the idea works would be the expensive way round.
//! Expert residency is a **caching problem**, and caching problems are decided by the access
//! trace, not by the hardware: if routing were uniform-random no policy could beat any other,
//! and if routing is skewed the win is bounded by how skewed it is. So the honest first
//! question is what the trace looks like, and that is answerable today.
//!
//! [`Policy::Optimal`] is included for exactly this reason. Belady's algorithm cannot be
//! implemented in a real engine — it requires knowing the future — but it is the **upper bound
//! no online policy can exceed**. Reporting LRU against Optimal says how much room is left. A
//! policy within a point or two of Optimal is finished work, however unsatisfying that feels;
//! a large gap is an invitation.
//!
//! [`Policy::StaticSplit`] models what llama.cpp does, so every measurement has the incumbent
//! next to it. A number with no baseline is decoration.

use std::collections::HashMap;

/// One expert, identified by the layer it lives in.
///
/// `u16` each: no shipping model has 65k layers or 65k experts per layer, and keeping this
/// four bytes matters because traces hold millions of them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ExpertRef {
    pub layer: u16,
    pub expert: u16,
}

impl ExpertRef {
    pub fn new(layer: u16, expert: u16) -> Self {
        Self { layer, expert }
    }
}

/// The experts a model actually touched, step by step.
///
/// One `Vec<ExpertRef>` per decode step, holding every expert activated across all layers for
/// that token. Captured from a real run, or generated by [`synthetic_trace`].
#[derive(Debug, Clone, Default)]
pub struct Trace {
    pub steps: Vec<Vec<ExpertRef>>,
}

impl Trace {
    /// Total expert activations across the trace — the denominator for hit rate.
    pub fn demands(&self) -> u64 {
        self.steps.iter().map(|s| s.len() as u64).sum()
    }

    /// Distinct experts the trace ever touches. If this is at or below the cache capacity,
    /// residency is trivially solved and any policy scores identically.
    pub fn working_set(&self) -> usize {
        let mut seen: Vec<ExpertRef> = self.steps.iter().flatten().copied().collect();
        seen.sort_unstable();
        seen.dedup();
        seen.len()
    }

    /// The most experts any single step needs. Capacity below this cannot be served.
    pub fn peak_step_demand(&self) -> usize {
        self.steps.iter().map(Vec::len).max().unwrap_or(0)
    }

    /// Distinct experts appearing in layers below `layer`.
    pub fn experts_in_layers_below(&self, layer: u16) -> usize {
        let mut seen: Vec<ExpertRef> =
            self.steps.iter().flatten().copied().filter(|e| e.layer < layer).collect();
        seen.sort_unstable();
        seen.dedup();
        seen.len()
    }

    /// The most generous static split that still fits in `capacity`.
    ///
    /// This is how a static baseline should be chosen: give the incumbent every slot it can
    /// legitimately use, so any remaining advantage belongs to the policy rather than to an
    /// unequal budget.
    pub fn widest_static_split(&self, capacity: u32) -> Policy {
        let max_layer = self.steps.iter().flatten().map(|e| e.layer).max().unwrap_or(0);
        let mut best = 0u16;
        for l in 1..=max_layer.saturating_add(1) {
            if self.experts_in_layers_below(l) <= capacity as usize {
                best = l;
            } else {
                break;
            }
        }
        Policy::StaticSplit { resident_layers: best }
    }
}

// ---------------------------------------------------------------------------
// Reading a captured trace
// ---------------------------------------------------------------------------

/// A trace read from a capture file, with its provenance header preserved verbatim.
///
/// The header is kept as the raw JSON line rather than parsed into fields. Two reasons: adding
/// a field to the capture tool must never break this loader, and a result is only citable if
/// the exact provenance that came with it survives intact — model, quantisation, prompt,
/// llama.cpp commit and capture date.
#[derive(Debug, Clone)]
pub struct LoadedTrace {
    pub header: String,
    pub trace: Trace,
}

/// Why a capture file could not be read.
#[derive(Debug)]
pub enum TraceLoadError {
    Io(std::io::Error),
    /// The file was empty, so there is not even a header.
    MissingHeader,
    /// The first line is not a `moearc-trace-v1` header.
    UnknownFormat(String),
    /// A step line could not be read. Malformed input is refused rather than skipped: a trace
    /// that silently drops steps would understate every miss count computed from it.
    MalformedStep {
        line: usize,
        reason: &'static str,
    },
    /// A header with no step lines after it.
    NoSteps,
}

impl std::fmt::Display for TraceLoadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "reading trace file: {e}"),
            Self::MissingHeader => write!(f, "trace file is empty: no header line"),
            Self::UnknownFormat(got) => {
                write!(f, "not a moearc-trace-v1 file; first line begins: {got}")
            }
            Self::MalformedStep { line, reason } => {
                write!(f, "malformed step on line {line}: {reason}")
            }
            Self::NoSteps => write!(f, "trace file has a header but no step lines"),
        }
    }
}

impl std::error::Error for TraceLoadError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(e) => Some(e),
            _ => None,
        }
    }
}

/// The key holding a step's activations. See `bench/traces/README.md` for the full format.
const EXPERTS_KEY: &str = "\"e\":[";

impl Trace {
    /// Read a trace from an NDJSON capture file.
    ///
    /// Line 1 is a header object; every line after it is one decode (or prefill) step. Only the
    /// `"e"` array is read from a step — a flat list of `layer, expert, layer, expert, …`. The
    /// parser is hand-rolled rather than using `serde_json` so that the simulation half of the
    /// crate keeps no runtime dependencies at all.
    pub fn from_ndjson_file<P: AsRef<std::path::Path>>(
        path: P,
    ) -> Result<LoadedTrace, TraceLoadError> {
        let text = std::fs::read_to_string(path).map_err(TraceLoadError::Io)?;
        Self::from_ndjson_str(&text)
    }

    /// Parse a trace already in memory. See [`Trace::from_ndjson_file`].
    pub fn from_ndjson_str(text: &str) -> Result<LoadedTrace, TraceLoadError> {
        let mut lines = text.lines().enumerate().filter(|(_, l)| !l.trim().is_empty());

        let (_, header) = lines.next().ok_or(TraceLoadError::MissingHeader)?;
        if !header.contains("\"format\":\"moearc-trace-v1\"") {
            return Err(TraceLoadError::UnknownFormat(header.chars().take(60).collect()));
        }

        let mut steps: Vec<Vec<ExpertRef>> = Vec::new();
        for (idx, line) in lines {
            let lineno = idx + 1;
            let bad = |reason| TraceLoadError::MalformedStep { line: lineno, reason };

            let start = line.find(EXPERTS_KEY).ok_or_else(|| bad("no \"e\":[...] field"))?
                + EXPERTS_KEY.len();
            let rest = &line[start..];
            let end = rest.find(']').ok_or_else(|| bad("unterminated \"e\" array"))?;

            let body = rest[..end].trim();
            let mut flat: Vec<u16> = Vec::new();
            if !body.is_empty() {
                for tok in body.split(',') {
                    let v: u16 = tok
                        .trim()
                        .parse()
                        .map_err(|_| bad("expected a non-negative integer below 65536"))?;
                    flat.push(v);
                }
            }
            if flat.len() % 2 != 0 {
                return Err(bad("odd number of integers; expected layer,expert pairs"));
            }
            steps.push(flat.chunks_exact(2).map(|c| ExpertRef::new(c[0], c[1])).collect());
        }

        if steps.is_empty() {
            return Err(TraceLoadError::NoSteps);
        }
        Ok(LoadedTrace { header: header.to_string(), trace: Trace { steps } })
    }
}

/// A residency policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Policy {
    /// Evict the expert unused for longest. The obvious online choice.
    Lru,
    /// Evict the expert used fewest times. Resists a one-off scan flushing a hot set, but
    /// cannot forget an expert that was hot early and is now cold.
    Lfu,
    /// Belady's optimal: evict whichever resident expert is needed furthest in the future.
    ///
    /// **Not implementable in a real engine** — it reads the future. It exists to bound what
    /// any online policy could achieve on this trace.
    Optimal,
    /// The incumbent: a fixed set of layers resident, the rest always fetched.
    ///
    /// Approximates llama.cpp's `--n-cpu-moe`. The approximation is deliberate and imperfect:
    /// llama.cpp offloads whole MoE *layers* to the CPU rather than caching experts, so it has
    /// no notion of a hit. Modelling it as "every expert in a resident layer hits, every
    /// expert elsewhere misses" is the closest comparable statement.
    StaticSplit { resident_layers: u16 },
}

impl Policy {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Lru => "lru",
            Self::Lfu => "lfu",
            Self::Optimal => "optimal (belady)",
            Self::StaticSplit { .. } => "static split",
        }
    }
}

/// What a simulation measured.
#[derive(Debug, Clone, PartialEq)]
pub struct Residency {
    pub policy: &'static str,
    pub capacity: u32,
    pub steps: u64,
    /// Total expert activations.
    pub demands: u64,
    /// Activations served from VRAM.
    pub hits: u64,
    /// Activations that required a fetch.
    pub misses: u64,
    /// Misses caused by an expert never having been resident, as opposed to having been
    /// evicted. Compulsory misses are unavoidable; the rest are the policy's fault.
    pub compulsory_misses: u64,
    /// Bytes moved across the bus.
    pub bytes_fetched: u64,
}

impl Residency {
    /// Fraction of activations served from VRAM.
    pub fn hit_rate(&self) -> f64 {
        if self.demands == 0 { 0.0 } else { self.hits as f64 / self.demands as f64 }
    }

    /// Misses that a perfect policy of the same capacity could in principle have avoided.
    pub fn avoidable_misses(&self) -> u64 {
        self.misses.saturating_sub(self.compulsory_misses)
    }

    /// Seconds of transfer this implies at a given link bandwidth. The number that actually
    /// matters: a hit rate is only interesting once converted into time.
    pub fn transfer_seconds(&self, bytes_per_second: f64) -> f64 {
        if bytes_per_second <= 0.0 {
            f64::INFINITY
        } else {
            self.bytes_fetched as f64 / bytes_per_second
        }
    }
}

/// Why a simulation could not run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SimError {
    /// Capacity cannot hold one step's activations, so the trace is unservable at any hit rate.
    CapacityBelowPeakDemand { capacity: u32, peak: usize },
    /// Capacity of zero.
    ZeroCapacity,
    /// A static split was asked to hold more experts than the cache capacity allows.
    ///
    /// 🔴 This exists because of a real error caught by the tests. `StaticSplit` originally
    /// ignored `capacity` altogether, so a comparison at 64 slots was silently measuring a
    /// static policy holding 128 experts against a dynamic one holding 64 — a two-to-one
    /// handicap, in the incumbent's favour, invisible in the output. A baseline that does not
    /// obey the same budget is not a baseline.
    StaticSplitExceedsCapacity { needs: usize, capacity: u32, resident_layers: u16 },
}

impl std::fmt::Display for SimError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CapacityBelowPeakDemand { capacity, peak } => write!(
                f,
                "capacity {capacity} cannot hold the {peak} experts one step activates — this \
                 trace is unservable at this capacity regardless of policy"
            ),
            Self::ZeroCapacity => write!(f, "capacity must be at least one expert"),
            Self::StaticSplitExceedsCapacity { needs, capacity, resident_layers } => write!(
                f,
                "a static split of the first {resident_layers} layers needs {needs} expert                  slots but capacity is {capacity} — comparing it against a dynamic policy at                  this capacity would hand it a larger budget"
            ),
        }
    }
}

impl std::error::Error for SimError {}

/// Replay `trace` through `policy` at `capacity` slots.
///
/// Experts needed by the current step are pinned for the duration of that step: evicting one
/// to make room for another in the same step would model a stall that does not exist, since a
/// real engine holds what it is about to use.
pub fn simulate(
    trace: &Trace,
    capacity: u32,
    policy: Policy,
    per_expert_bytes: u64,
) -> Result<Residency, SimError> {
    if capacity == 0 {
        return Err(SimError::ZeroCapacity);
    }
    let peak = trace.peak_step_demand();
    if (capacity as usize) < peak {
        return Err(SimError::CapacityBelowPeakDemand { capacity, peak });
    }

    let mut stats = Residency {
        policy: policy.name(),
        capacity,
        steps: trace.steps.len() as u64,
        demands: 0,
        hits: 0,
        misses: 0,
        compulsory_misses: 0,
        bytes_fetched: 0,
    };

    // The static split needs no cache state: residency is decided by layer, once, forever.
    if let Policy::StaticSplit { resident_layers } = policy {
        // Hold the baseline to the same budget as every other policy.
        let needs = trace.experts_in_layers_below(resident_layers);
        if needs > capacity as usize {
            return Err(SimError::StaticSplitExceedsCapacity { needs, capacity, resident_layers });
        }
        for step in &trace.steps {
            for e in step {
                stats.demands += 1;
                if e.layer < resident_layers {
                    stats.hits += 1;
                } else {
                    stats.misses += 1;
                    stats.bytes_fetched += per_expert_bytes;
                }
            }
        }
        // Every miss here recurs forever by construction, so none is compulsory in the usual
        // sense; leaving the count at zero states that none of them is avoidable by policy.
        return Ok(stats);
    }

    let next_use = (policy == Policy::Optimal).then(|| NextUse::build(trace));

    let mut resident: Vec<ExpertRef> = Vec::with_capacity(capacity as usize);
    let mut last_used: HashMap<ExpertRef, u64> = HashMap::new();
    let mut use_count: HashMap<ExpertRef, u64> = HashMap::new();
    let mut ever_seen: HashMap<ExpertRef, ()> = HashMap::new();
    let mut clock: u64 = 0;

    for (step_idx, step) in trace.steps.iter().enumerate() {
        // Experts required now, so eviction cannot touch them.
        let mut pinned: Vec<ExpertRef> = step.clone();
        pinned.sort_unstable();
        pinned.dedup();

        for &e in step {
            clock += 1;
            stats.demands += 1;
            *use_count.entry(e).or_insert(0) += 1;

            if resident.contains(&e) {
                stats.hits += 1;
                last_used.insert(e, clock);
                continue;
            }

            stats.misses += 1;
            stats.bytes_fetched += per_expert_bytes;
            if ever_seen.insert(e, ()).is_none() {
                stats.compulsory_misses += 1;
            }

            if resident.len() >= capacity as usize {
                let victim = choose_victim(
                    &resident,
                    &pinned,
                    &last_used,
                    &use_count,
                    next_use.as_ref(),
                    step_idx,
                    policy,
                );
                // Pinning cannot starve eviction: capacity >= peak step demand is checked
                // above, so at least one resident expert is always unpinned.
                let victim = victim.expect("capacity >= peak demand guarantees an unpinned slot");
                resident.retain(|&r| r != victim);
            }
            resident.push(e);
            last_used.insert(e, clock);
        }
    }

    Ok(stats)
}

fn choose_victim(
    resident: &[ExpertRef],
    pinned: &[ExpertRef],
    last_used: &HashMap<ExpertRef, u64>,
    use_count: &HashMap<ExpertRef, u64>,
    next_use: Option<&NextUse>,
    step_idx: usize,
    policy: Policy,
) -> Option<ExpertRef> {
    // `pinned` is sorted and deduplicated by the caller, so a binary search is exactly
    // equivalent to `contains` here — and necessary: at the capacities a real card gives
    // (thousands of slots) a linear scan of the pin list inside a scan of the resident set
    // makes a full-length trace take hours instead of seconds.
    let candidates = resident.iter().copied().filter(|r| pinned.binary_search(r).is_err());
    match policy {
        Policy::Lru => candidates.min_by_key(|e| last_used.get(e).copied().unwrap_or(0)),
        Policy::Lfu => candidates.min_by_key(|e| use_count.get(e).copied().unwrap_or(0)),
        Policy::Optimal => {
            let nu = next_use.expect("Optimal requires a next-use index");
            // Furthest next use wins; never-used-again is furthest of all.
            candidates.max_by_key(|e| nu.after(*e, step_idx).unwrap_or(usize::MAX))
        }
        Policy::StaticSplit { .. } => unreachable!("static split does not evict"),
    }
}

/// Step indices at which each expert is used, for Belady's lookahead.
struct NextUse {
    occurrences: HashMap<ExpertRef, Vec<usize>>,
}

impl NextUse {
    fn build(trace: &Trace) -> Self {
        let mut occurrences: HashMap<ExpertRef, Vec<usize>> = HashMap::new();
        for (i, step) in trace.steps.iter().enumerate() {
            for &e in step {
                let v = occurrences.entry(e).or_default();
                // Steps arrive in order and one step may name an expert twice; keep it sorted
                // and unique so the binary search below is valid.
                if v.last() != Some(&i) {
                    v.push(i);
                }
            }
        }
        Self { occurrences }
    }

    /// The first step strictly after `step` at which `e` is used again, if ever.
    fn after(&self, e: ExpertRef, step: usize) -> Option<usize> {
        let v = self.occurrences.get(&e)?;
        match v.binary_search(&step) {
            Ok(i) => v.get(i + 1).copied(),
            Err(i) => v.get(i).copied(),
        }
    }
}

/// Generate a routing trace with controllable skew, for studying how much locality a policy
/// needs before it beats a static split.
///
/// `skew` shapes expert selection within each layer:
/// - `0.0` — uniform. No policy can beat any other; a cache is pointless.
/// - `1.0` — strongly concentrated on a few experts per layer.
///
/// 🔴 **This is a study instrument, not evidence.** Real MoE routing is known to be skewed,
/// but *how* skewed is a property of a specific model and prompt distribution, and no number
/// produced from this function may be reported as a measurement of any real model. Capture a
/// trace for that.
pub fn synthetic_trace(
    steps: usize,
    layers: u16,
    experts_per_layer: u16,
    active_per_layer: u16,
    skew: f64,
    seed: u64,
) -> Trace {
    let mut rng = Rng::new(seed);
    let skew = skew.clamp(0.0, 1.0);
    let mut out = Vec::with_capacity(steps);

    for _ in 0..steps {
        let mut activations = Vec::with_capacity((layers as usize) * (active_per_layer as usize));
        for layer in 0..layers {
            let mut chosen: Vec<u16> = Vec::with_capacity(active_per_layer as usize);
            while chosen.len() < active_per_layer as usize {
                // Raising a uniform to a power > 1 biases toward zero; skew controls how hard.
                let u = rng.next_f64();
                let shaped = u.powf(1.0 + skew * 6.0);
                let e = (shaped * experts_per_layer as f64) as u16;
                let e = e.min(experts_per_layer - 1);
                if !chosen.contains(&e) {
                    chosen.push(e);
                }
            }
            activations.extend(chosen.into_iter().map(|e| ExpertRef::new(layer, e)));
        }
        out.push(activations);
    }
    Trace { steps: out }
}

/// A small deterministic PRNG (xorshift64*).
///
/// Hand-rolled rather than pulling in `rand`: simulation results must be reproducible across
/// machines and versions forever, and a dependency that changes its generator between releases
/// would silently invalidate every recorded comparison.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(if seed == 0 { 0x9E37_79B9_7F4A_7C15 } else { seed })
    }
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn next_f64(&mut self) -> f64 {
        // 53 bits of mantissa, uniform in [0, 1).
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MIB: u64 = 1 << 20;

    fn trace_of(steps: &[&[(u16, u16)]]) -> Trace {
        Trace {
            steps: steps
                .iter()
                .map(|s| s.iter().map(|&(l, e)| ExpertRef::new(l, e)).collect())
                .collect(),
        }
    }

    #[test]
    fn everything_resident_means_only_compulsory_misses() {
        let t = trace_of(&[&[(0, 0), (0, 1)], &[(0, 0), (0, 1)], &[(0, 1), (0, 0)]]);
        let r = simulate(&t, 8, Policy::Lru, MIB).unwrap();
        assert_eq!(r.demands, 6);
        assert_eq!(r.misses, 2, "only the first touch of each expert should miss");
        assert_eq!(r.compulsory_misses, 2);
        assert_eq!(r.avoidable_misses(), 0);
        assert_eq!(r.bytes_fetched, 2 * MIB);
    }

    #[test]
    fn lru_evicts_the_least_recently_used() {
        // Capacity 2. Touch a, b, then c (evicts a), then a again -> miss.
        let t = trace_of(&[&[(0, 0)], &[(0, 1)], &[(0, 2)], &[(0, 0)]]);
        let r = simulate(&t, 2, Policy::Lru, MIB).unwrap();
        assert_eq!(r.misses, 4);
        assert_eq!(r.compulsory_misses, 3);
        assert_eq!(r.avoidable_misses(), 1, "re-fetching a is the eviction's cost");
    }

    #[test]
    fn optimal_is_never_worse_than_lru() {
        // The defining property of Belady's algorithm, checked over varied traces rather
        // than asserted once.
        for seed in [1u64, 7, 42, 1234] {
            for skew in [0.0, 0.3, 0.7, 1.0] {
                let t = synthetic_trace(120, 4, 16, 2, skew, seed);
                for cap in [8u32, 16, 32] {
                    let lru = simulate(&t, cap, Policy::Lru, MIB).unwrap();
                    let opt = simulate(&t, cap, Policy::Optimal, MIB).unwrap();
                    assert!(
                        opt.misses <= lru.misses,
                        "optimal ({}) worse than lru ({}) at cap {cap}, skew {skew}, seed {seed}",
                        opt.misses,
                        lru.misses
                    );
                }
            }
        }
    }

    #[test]
    fn optimal_beats_lru_on_a_trace_designed_to_fool_recency() {
        // Capacity 2, cycling three experts: LRU always evicts the one needed next.
        let steps: Vec<&[(u16, u16)]> =
            vec![&[(0, 0)], &[(0, 1)], &[(0, 2)], &[(0, 0)], &[(0, 1)], &[(0, 2)], &[(0, 0)]];
        let t = trace_of(&steps);
        let lru = simulate(&t, 2, Policy::Lru, MIB).unwrap();
        let opt = simulate(&t, 2, Policy::Optimal, MIB).unwrap();
        assert!(opt.misses < lru.misses, "opt {} vs lru {}", opt.misses, lru.misses);
    }

    #[test]
    fn a_uniform_trace_gives_no_policy_an_advantage() {
        // The honest null result: with no locality there is nothing for a cache to exploit,
        // and a dynamic policy cannot justify itself.
        let t = synthetic_trace(400, 8, 64, 4, 0.0, 99);
        let lru = simulate(&t, 64, Policy::Lru, MIB).unwrap();
        let opt = simulate(&t, 64, Policy::Optimal, MIB).unwrap();
        let gain = lru.hit_rate() - opt.hit_rate();
        assert!(gain.abs() < 0.25, "unexpectedly large gap on a uniform trace: {gain}");
    }

    #[test]
    fn skew_is_what_makes_caching_pay() {
        let flat = synthetic_trace(400, 8, 64, 4, 0.0, 5);
        let peaked = synthetic_trace(400, 8, 64, 4, 1.0, 5);
        let a = simulate(&flat, 64, Policy::Lru, MIB).unwrap();
        let b = simulate(&peaked, 64, Policy::Lru, MIB).unwrap();
        assert!(
            b.hit_rate() > a.hit_rate() + 0.2,
            "skewed routing should cache far better: flat {:.3} vs peaked {:.3}",
            a.hit_rate(),
            b.hit_rate()
        );
    }

    #[test]
    fn a_static_split_may_not_exceed_the_shared_capacity() {
        // The guard for the error described on StaticSplitExceedsCapacity: eight layers of
        // 32 experts, so four resident layers need 128 slots and 64 were offered.
        let t = synthetic_trace(300, 8, 32, 4, 0.8, 11);
        let e = simulate(&t, 64, Policy::StaticSplit { resident_layers: 4 }, MIB).unwrap_err();
        assert!(matches!(e, SimError::StaticSplitExceedsCapacity { .. }));
    }

    #[test]
    fn dynamic_residency_beats_a_fairly_budgeted_static_split() {
        // The project's central claim, tested at equal capacity. The baseline is given the
        // widest static split its budget allows, so nothing here is stacked in our favour.
        let t = synthetic_trace(300, 8, 32, 4, 0.8, 11);
        let capacity = 64;
        let baseline = t.widest_static_split(capacity);
        let stat = simulate(&t, capacity, baseline, MIB).unwrap();
        let lru = simulate(&t, capacity, Policy::Lru, MIB).unwrap();
        let opt = simulate(&t, capacity, Policy::Optimal, MIB).unwrap();
        eprintln!(
            "capacity {capacity}: static {:.3}, lru {:.3}, optimal {:.3}",
            stat.hit_rate(),
            lru.hit_rate(),
            opt.hit_rate()
        );
        assert!(
            lru.hit_rate() > stat.hit_rate(),
            "dynamic residency should beat an equally budgeted static split on a skewed              trace: lru {:.3} vs static {:.3}",
            lru.hit_rate(),
            stat.hit_rate()
        );
        assert!(opt.hit_rate() >= lru.hit_rate());
    }

    #[test]
    fn capacity_below_a_single_step_is_refused_rather_than_thrashing() {
        let t = trace_of(&[&[(0, 0), (0, 1), (0, 2)]]);
        let e = simulate(&t, 2, Policy::Lru, MIB).unwrap_err();
        assert!(matches!(e, SimError::CapacityBelowPeakDemand { .. }));
        assert!(e.to_string().contains("regardless of policy"));
    }

    #[test]
    fn transfer_time_converts_a_hit_rate_into_something_meaningful() {
        let t = synthetic_trace(100, 4, 32, 2, 0.5, 3);
        let r = simulate(&t, 16, Policy::Lru, 96 * MIB).unwrap();
        // ~13.4 GB/s was measured for the host-to-device path on this hardware.
        let secs = r.transfer_seconds(13.4e9);
        assert!(secs > 0.0 && secs.is_finite());
        assert_eq!(r.transfer_seconds(0.0), f64::INFINITY);
    }

    #[test]
    fn the_generator_is_reproducible() {
        let a = synthetic_trace(50, 4, 16, 2, 0.6, 777);
        let b = synthetic_trace(50, 4, 16, 2, 0.6, 777);
        assert_eq!(a.steps, b.steps, "same seed must give the same trace, forever");
    }

    #[test]
    fn trace_reports_its_own_shape() {
        let t = synthetic_trace(10, 4, 8, 2, 0.5, 1);
        assert_eq!(t.demands(), 10 * 4 * 2);
        assert_eq!(t.peak_step_demand(), 8);
        assert!(t.working_set() <= 32);
    }

    const SAMPLE: &str = concat!(
        "{\"format\":\"moearc-trace-v1\",\"phase\":\"decode\",\"n_layer\":2}\n",
        "{\"step\":0,\"phase\":\"decode\",\"pos\":5,\"e\":[0,7,0,9,1,3]}\n",
        "{\"step\":1,\"phase\":\"decode\",\"pos\":6,\"e\":[0,7,1,3,1,4]}\n"
    );

    #[test]
    fn a_capture_file_round_trips_into_a_trace() {
        let loaded = Trace::from_ndjson_str(SAMPLE).unwrap();
        assert!(loaded.header.contains("moearc-trace-v1"), "header must be kept verbatim");
        assert_eq!(loaded.trace.steps.len(), 2);
        assert_eq!(
            loaded.trace.steps[0],
            vec![ExpertRef::new(0, 7), ExpertRef::new(0, 9), ExpertRef::new(1, 3)]
        );
        assert_eq!(loaded.trace.demands(), 6);
        assert_eq!(loaded.trace.working_set(), 4);
        assert_eq!(loaded.trace.peak_step_demand(), 3);
    }

    #[test]
    fn a_loaded_trace_simulates_like_any_other() {
        let t = Trace::from_ndjson_str(SAMPLE).unwrap().trace;
        let r = simulate(&t, 8, Policy::Lru, MIB).unwrap();
        assert_eq!(r.demands, 6);
        assert_eq!(r.compulsory_misses, 4, "four distinct experts, each fetched once");
        assert_eq!(r.hits, 2, "(0,7) and (1,3) recur on the second step");
    }

    #[test]
    fn a_malformed_step_is_refused_rather_than_skipped() {
        // Silently dropping a step would understate every miss count taken from the trace.
        let odd = concat!("{\"format\":\"moearc-trace-v1\"}\n", "{\"step\":0,\"e\":[0,7,1]}\n");
        let e = Trace::from_ndjson_str(odd).unwrap_err();
        assert!(matches!(e, TraceLoadError::MalformedStep { line: 2, .. }), "{e}");
        assert!(e.to_string().contains("layer,expert pairs"));

        let junk = concat!("{\"format\":\"moearc-trace-v1\"}\n", "{\"step\":0,\"e\":[0,x]}\n");
        assert!(matches!(
            Trace::from_ndjson_str(junk).unwrap_err(),
            TraceLoadError::MalformedStep { .. }
        ));

        let no_field = concat!("{\"format\":\"moearc-trace-v1\"}\n", "{\"step\":0}\n");
        assert!(matches!(
            Trace::from_ndjson_str(no_field).unwrap_err(),
            TraceLoadError::MalformedStep { .. }
        ));
    }

    #[test]
    fn a_file_that_is_not_a_trace_is_rejected_by_its_header() {
        assert!(matches!(Trace::from_ndjson_str("").unwrap_err(), TraceLoadError::MissingHeader));
        assert!(matches!(
            Trace::from_ndjson_str("{\"hello\":1}\n").unwrap_err(),
            TraceLoadError::UnknownFormat(_)
        ));
        assert!(matches!(
            Trace::from_ndjson_str("{\"format\":\"moearc-trace-v1\"}\n").unwrap_err(),
            TraceLoadError::NoSteps
        ));
    }

    #[test]
    fn the_real_captured_trace_loads_and_has_the_shape_the_model_implies() {
        // Guards the committed capture against silent corruption, and pins the two facts the
        // whole residency argument rests on: 40 routed layers, 8 experts each.
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../bench/traces/qwen35moe-prose.decode.ndjson"
        );
        let Ok(loaded) = Trace::from_ndjson_file(path) else {
            // The trace is committed, but do not fail a checkout that omitted it.
            eprintln!("skipping: {path} not present");
            return;
        };
        assert!(loaded.header.contains("Qwen3.6-35B-A3B"));
        assert_eq!(loaded.trace.steps.len(), 1024);
        assert!(loaded.trace.steps.iter().all(|s| s.len() == 320), "40 layers x 8 experts");
        assert!(loaded.trace.working_set() <= 40 * 256);
    }
}
