//! Property tests over a corpus of adversarial inputs.
//!
//! `tests/data/adversarial_corpus.json` was generated by sweeping a prior-art implementation
//! over thousands of structured and randomised configurations. Its *outputs* are that
//! implementation's choices and we are deliberately not bound by them — MoEArc's planner makes
//! different decisions on purpose. Its *inputs*, though, are a genuinely hostile corpus:
//! budgets of zero, single-byte pages, expert counts above any real model, reserves larger than
//! the whole budget. Cheap to keep, and better than anything hand-written.
//!
//! So the corpus is used for invariants, not for agreement. Whatever the planner decides on
//! any of these shapes, it must never decide something unsafe.

use moearc_engine::memory::{Context, DeviceMemory, Headroom, ModelFootprint, Policy, plan};
use serde::Deserialize;

#[derive(Deserialize)]
struct PlanArgs {
    budget_bytes: i64,
    per_expert_bytes: i64,
    cache_per_page: i64,
    num_experts: i64,
    total_experts: i64,
    kv_reserve_pages: i64,
    max_slots: i64,
}

#[derive(Deserialize)]
struct PlanCase {
    args: PlanArgs,
}

#[derive(Deserialize)]
struct Corpus {
    plan: Vec<PlanCase>,
}

fn corpus() -> Corpus {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/data/adversarial_corpus.json");
    let raw =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("corpus missing at {path}: {e}"));
    serde_json::from_str(&raw).expect("corpus is not valid JSON")
}

/// Translate a corpus row into MoEArc's types, or `None` if it cannot be represented.
///
/// The rows that cannot be represented are themselves the point. A negative budget is a
/// legitimate intermediate in a signed design and something that implementation had to detect
/// after the fact; here it is simply not expressible, so an entire class of failure is designed
/// out rather than guarded against.
fn as_inputs(a: &PlanArgs) -> Option<(DeviceMemory, ModelFootprint, Policy)> {
    if a.budget_bytes < 0
        || a.per_expert_bytes <= 0
        || a.cache_per_page <= 0
        || a.num_experts <= 0
        || a.total_experts <= 0
        || a.kv_reserve_pages < 0
        || a.max_slots <= 0
        || a.num_experts > a.total_experts
    {
        return None;
    }
    Some((
        DeviceMemory { total_bytes: a.budget_bytes as u64, free_bytes: a.budget_bytes as u64 },
        ModelFootprint {
            dense_weights_bytes: 0,
            per_expert_bytes: a.per_expert_bytes as u64,
            total_experts: a.total_experts.min(u32::MAX as i64) as u32,
            active_experts: a.num_experts.min(u32::MAX as i64) as u32,
            kv_bytes_per_token: a.cache_per_page as u64,
        },
        Policy {
            // No headroom and one token per page, so the corpus maps across exactly.
            headroom: Headroom::Bytes(0),
            page_tokens: 1,
            min_context_tokens: a.kv_reserve_pages.min(u32::MAX as i64) as u32,
            bias: Default::default(),
            max_resident_experts: Some(a.max_slots.min(u32::MAX as i64) as u32),
        },
    ))
}

#[test]
fn no_plan_over_commits_the_device() {
    let c = corpus();
    let (mut planned, mut refused, mut skipped) = (0usize, 0usize, 0usize);

    for (i, case) in c.plan.iter().enumerate() {
        let Some((device, model, policy)) = as_inputs(&case.args) else {
            skipped += 1;
            continue;
        };
        match plan(device, &model, &policy, Context::Largest) {
            Ok(a) => {
                // The invariant the whole module exists to guarantee.
                assert!(
                    a.committed_bytes(&model) + a.headroom_bytes <= device.free_bytes,
                    "case {i}: committed {} + headroom {} exceeds free {}",
                    a.committed_bytes(&model),
                    a.headroom_bytes,
                    device.free_bytes
                );
                // Below the active-expert floor, every token stalls on a fetch. A plan that
                // returns Ok while violating it is worse than one that fails.
                assert!(
                    a.resident_experts >= model.active_experts,
                    "case {i}: {} resident is below the {} active floor",
                    a.resident_experts,
                    model.active_experts
                );
                assert!(
                    a.resident_experts <= model.total_experts,
                    "case {i}: more slots resident than the model has experts"
                );
                assert!(
                    a.context_tokens >= policy.min_context_tokens,
                    "case {i}: served {} tokens, below the {} minimum",
                    a.context_tokens,
                    policy.min_context_tokens
                );
                // A stated reason for every decision, so the CLI always has something to show.
                assert!(!a.rationale.is_empty(), "case {i}: no rationale");
                planned += 1;
            }
            Err(_) => refused += 1,
        }
    }

    // Guard against a corpus that exercises only one branch, which would make this vacuous.
    assert!(planned > 200, "only {planned} plans succeeded — corpus is not exercising success");
    assert!(refused > 200, "only {refused} refusals — corpus is not exercising failure");
    eprintln!(
        "corpus: {planned} planned, {refused} refused, {skipped} unrepresentable \
         (negative or zero-valued inputs a signed design has to guard against)"
    );
}

#[test]
fn planning_is_deterministic() {
    let c = corpus();
    for case in c.plan.iter().take(400) {
        let Some((device, model, policy)) = as_inputs(&case.args) else { continue };
        let a = plan(device, &model, &policy, Context::Largest);
        let b = plan(device, &model, &policy, Context::Largest);
        assert_eq!(a, b, "planning must be a pure function of its inputs");
    }
}

#[test]
fn a_requested_context_is_either_served_in_full_or_refused() {
    let c = corpus();
    let mut checked = 0usize;
    for case in c.plan.iter() {
        let Some((device, model, policy)) = as_inputs(&case.args) else { continue };
        let Ok(largest) = plan(device, &model, &policy, Context::Largest) else { continue };
        if largest.context_tokens == 0 {
            continue;
        }
        // Ask for exactly what the greedy plan achieved: it must still be satisfiable.
        let want = Context::Tokens(largest.context_tokens);
        let a = plan(device, &model, &policy, want)
            .unwrap_or_else(|e| panic!("refused a context it had just achieved: {e}"));
        assert!(a.context_tokens >= largest.context_tokens);
        assert!(a.committed_bytes(&model) + a.headroom_bytes <= device.free_bytes);
        checked += 1;
        if checked >= 500 {
            break;
        }
    }
    assert!(checked > 100, "only checked {checked} cases");
}
